
[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"  # Underline | Block

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none" # "full"
dynamic_title = false
dynamic_padding = false
# multiplier = 3
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 140
lines = 70

[window.padding]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000

[selection]
save_to_clipboard  = true

[general]
live_config_reload = true
import = [
  # "/home/jacky/.config/alacritty/colors.toml",
  "/home/jacky/.config/alacritty/colors2.toml",
  "/home/jacky/.config/alacritty/fonts.toml",
  "/home/jacky/.config/alacritty/colorschemes/Tokyo_night.toml"
]

[terminal.shell]
program = "tmux"
