[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.bright]
black   = "#928374"
blue    = "#83a598"
cyan    = "#8ec07c"
green   = "#b8bb26"
magenta = "#d3869b"
red     = "#fb4934"
white   = "#ebdbb2"
yellow  = "#fabd2f"

[colors.cursor]
cursor = "#bdae93"
text   = "CellForeground"

[colors.footer_bar]
background = "#171825"
foreground = "#232323"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black   = "#282828"
blue    = "#458588"
cyan    = "#689d6a"
green   = "#98971a"
magenta = "#b16286"
red     = "#cc241d"
white   = "#ebdbb2"
yellow  = "#d79921"

[colors.search.focused_match]
background = "CellBackground"
foreground = "#d5c4a1"

[colors.search.matches]
background = "CellBackground"
foreground = "#d5c4a1"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"
