[font]
size = 14
builtin_box_drawing = false

[font.bold]
# family = "JetBrainsMono Nerd Font"
family = "FiraCode Nerd Font"
style  = "SemiBold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style  = "SemiBold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style  = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style  = "SemiBold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = -1
y = -1
