# QuickShell Recent Applications
# Format: name|exec|icon

Deluge|deluge-gtk|󰌛
Viber|/opt/viber/Viber|󰣆
Files|nemo|󰉋
LM Studio|lm-studio|󰣆
Windsurf|/usr/share/windsurf/windsurf|󰨞
Windscribe|/opt/windscribe/Windscribe|󰣆
Zed|/home/jacky/.local/zed.app/bin/zed|󰣆
PortProton|portproton|󰣆
Obsidian|/usr/bin/obsidian|󰣆
Google Chrome|/usr/bin/google-chrome-stable|󰊯
Terminal|alacritty|󰆍

