# QuickShell Recent Applications
# Format: name|exec|icon

PortProton|portproton|󰣆
Files|nemo|󰉋
Deluge|deluge-gtk|󰌛
Zen Browser|/opt/zen-browser-bin/zen-bin|󰖟
Viber|/opt/viber/Viber|󰣆
Telegram|Telegram --|󰕐
Oracle VirtualBox|VirtualBox|󰣆
LM Studio|lm-studio|󰣆
Terminal|alacritty|󰆍
Windsurf|/usr/share/windsurf/windsurf|󰨞
Windscribe|/opt/windscribe/Windscribe|󰣆
Zed|/home/jacky/.local/zed.app/bin/zed|󰣆
Obsidian|/usr/bin/obsidian|󰣆
Google Chrome|/usr/bin/google-chrome-stable|󰊯

