# QuickShell Recent Applications
# Format: name|exec|icon

Telegram|Telegram --|󰕐
Zen Browser|/opt/zen-browser-bin/zen-bin|󰖟
Files|nemo|󰉋
Viber|/opt/viber/Viber|󰣆
Oracle VirtualBox|VirtualBox|󰣆
Deluge|deluge-gtk|󰌛
LM Studio|lm-studio|󰣆
Terminal|alacritty|󰆍
Windsurf|/usr/share/windsurf/windsurf|󰨞
Windscribe|/opt/windscribe/Windscribe|󰣆
Zed|/home/jacky/.local/zed.app/bin/zed|󰣆
PortProton|portproton|󰣆
Obsidian|/usr/bin/obsidian|󰣆
Google Chrome|/usr/bin/google-chrome-stable|󰊯

